/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import model.bean.Lixeira;
import model.bean.Usuario;
import model.dao.LixeiraDAO;
import model.dao.UsuarioDAO;

/**
 *
 * @author Leandro Max
 */
public class LixeiraScreen extends javax.swing.JFrame {
    
    Usuario user;
    private Usuario activeUser;
    private Lixeira lixeira;
    
    /**
     * Creates new form LixeiraScreen
     */
    public LixeiraScreen() {
        initComponents();
        
        user = new Usuario();
        LixeiraDAO lixeiraDAO = new LixeiraDAO();
        
        for( Lixeira l: lixeiraDAO.read())
        {
            jComboBoxLixeiras.addItem(l);  
        }
    }
    
    /**
     * Contrutor 2 
     * @param activeUser 
     */
    public LixeiraScreen(Usuario activeUser)
    {
        initComponents();
        this.activeUser = new Usuario();
        this.activeUser = activeUser;
        LixeiraDAO lixeiraDAO = new LixeiraDAO();
        
        // Preenche as caixas de seleção com as lixeiras disponíveis
        for( Lixeira l: lixeiraDAO.read())
        {
            jComboBoxLixeiras.addItem(l);     
        }
        jlUsuarioNome.setText(this.activeUser.getNome());
        jlPontuacaoUsuario.setText(Integer.toString(this.activeUser.getPontuacao()));
        jftfCelular.setText(this.activeUser.getCelular());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelDadosLixeira = new javax.swing.JPanel();
        jLabelSelecionarLixeira = new javax.swing.JLabel();
        jComboBoxLixeiras = new javax.swing.JComboBox<>();
        jButtonCarregaLixeira = new javax.swing.JButton();
        jLabelCapUtilizada = new javax.swing.JLabel();
        jLabelCapUtil = new javax.swing.JLabel();
        lbCapacidadeTotal = new javax.swing.JLabel();
        lbCapacidadeTotalResult = new javax.swing.JLabel();
        jPanelDadosUsuario = new javax.swing.JPanel();
        jButtonCarregarUsuario = new javax.swing.JButton();
        jLabelDigiteCelular = new javax.swing.JLabel();
        jftfCelular = new javax.swing.JFormattedTextField();
        jlUsuarioNome = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlPontuacao = new javax.swing.JLabel();
        jlPontuacaoUsuario = new javax.swing.JLabel();
        jPanelDadosdoLixo = new javax.swing.JPanel();
        jComboBoxTipoDeLixo = new javax.swing.JComboBox<>();
        jLabelTipoDoLixo = new javax.swing.JLabel();
        btCadastrarLixo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbVoltar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Interface da Lixeira");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 0, 133, 17);

        jPanelDadosLixeira.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Lixeira"));

        jLabelSelecionarLixeira.setText("Selecione a lixeira:");

        jComboBoxLixeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLixeirasActionPerformed(evt);
            }
        });

        jButtonCarregaLixeira.setText("Carregar Lixeira");
        jButtonCarregaLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarregaLixeiraActionPerformed(evt);
            }
        });

        jLabelCapUtil.setText("Capacidade Utilizada:");

        lbCapacidadeTotal.setText("Capacidade Total:");

        javax.swing.GroupLayout jPanelDadosLixeiraLayout = new javax.swing.GroupLayout(jPanelDadosLixeira);
        jPanelDadosLixeira.setLayout(jPanelDadosLixeiraLayout);
        jPanelDadosLixeiraLayout.setHorizontalGroup(
            jPanelDadosLixeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLixeiraLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabelCapUtil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCapUtilizada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelDadosLixeiraLayout.createSequentialGroup()
                .addGroup(jPanelDadosLixeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCapacidadeTotal)
                    .addComponent(jLabelSelecionarLixeira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosLixeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosLixeiraLayout.createSequentialGroup()
                        .addComponent(jComboBoxLixeiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCarregaLixeira))
                    .addComponent(lbCapacidadeTotalResult))
                .addGap(0, 112, Short.MAX_VALUE))
        );
        jPanelDadosLixeiraLayout.setVerticalGroup(
            jPanelDadosLixeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLixeiraLayout.createSequentialGroup()
                .addGroup(jPanelDadosLixeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelecionarLixeira)
                    .addComponent(jComboBoxLixeiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCarregaLixeira))
                .addGap(9, 9, 9)
                .addGroup(jPanelDadosLixeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCapacidadeTotal)
                    .addComponent(lbCapacidadeTotalResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLixeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCapUtilizada, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCapUtil))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelDadosLixeira);
        jPanelDadosLixeira.setBounds(10, 28, 370, 120);

        jPanelDadosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Usuário"));

        jButtonCarregarUsuario.setText("Carregar Usuário");
        jButtonCarregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarregarUsuarioActionPerformed(evt);
            }
        });

        jLabelDigiteCelular.setText("Digite o celular do Usuário: ");

        try {
            jftfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlUsuario.setText("Usuário:");

        jlPontuacao.setText("Pontuação:");

        javax.swing.GroupLayout jPanelDadosUsuarioLayout = new javax.swing.GroupLayout(jPanelDadosUsuario);
        jPanelDadosUsuario.setLayout(jPanelDadosUsuarioLayout);
        jPanelDadosUsuarioLayout.setHorizontalGroup(
            jPanelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosUsuarioLayout.createSequentialGroup()
                        .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(jButtonCarregarUsuario))
                    .addGroup(jPanelDadosUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDigiteCelular)
                            .addGroup(jPanelDadosUsuarioLayout.createSequentialGroup()
                                .addComponent(jlUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlUsuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDadosUsuarioLayout.createSequentialGroup()
                                .addComponent(jlPontuacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlPontuacaoUsuario)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDadosUsuarioLayout.setVerticalGroup(
            jPanelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDigiteCelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCarregarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuario)
                    .addComponent(jlUsuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPontuacao)
                    .addComponent(jlPontuacaoUsuario))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelDadosUsuario);
        jPanelDadosUsuario.setBounds(10, 147, 370, 150);

        jPanelDadosdoLixo.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Lixo"));

        jComboBoxTipoDeLixo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Plastico", "Papel", "Vidro", "Metal" }));
        jComboBoxTipoDeLixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDeLixoActionPerformed(evt);
            }
        });

        jLabelTipoDoLixo.setText("Tipo do lixo: ");

        btCadastrarLixo.setText("Cadastrar Lixo");
        btCadastrarLixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarLixoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosdoLixoLayout = new javax.swing.GroupLayout(jPanelDadosdoLixo);
        jPanelDadosdoLixo.setLayout(jPanelDadosdoLixoLayout);
        jPanelDadosdoLixoLayout.setHorizontalGroup(
            jPanelDadosdoLixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosdoLixoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosdoLixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosdoLixoLayout.createSequentialGroup()
                        .addComponent(jLabelTipoDoLixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoDeLixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCadastrarLixo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDadosdoLixoLayout.setVerticalGroup(
            jPanelDadosdoLixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosdoLixoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosdoLixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoDoLixo)
                    .addComponent(jComboBoxTipoDeLixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCadastrarLixo)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelDadosdoLixo);
        jPanelDadosdoLixo.setBounds(10, 320, 370, 120);

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbVoltar)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jbVoltar)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 450, 360, 50);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(411, 623));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoDeLixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDeLixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoDeLixoActionPerformed

    private void jComboBoxLixeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLixeirasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLixeirasActionPerformed

    private void jButtonCarregaLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarregaLixeiraActionPerformed
        LixeiraDAO dao = new LixeiraDAO();
        lixeira = new Lixeira();
        lixeira = (Lixeira)jComboBoxLixeiras.getSelectedItem();
        lixeira = dao.getLixeiraById(lixeira.getId());
        System.out.println("Lixeira ID: " + lixeira.getId() + "Capacidade total: " + lixeira.getCapacidadeTotal() + "Cap Util: " + lixeira.getCapacidadeUtilizada() );
        lbCapacidadeTotalResult.setText(Integer.toString(lixeira.getCapacidadeTotal()));
        jLabelCapUtilizada.setText(Integer.toString(lixeira.getCapacidadeUtilizada()));
    }//GEN-LAST:event_jButtonCarregaLixeiraActionPerformed

    private void jButtonCarregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarregarUsuarioActionPerformed
        UsuarioDAO dao = new UsuarioDAO();
        
        String tel = jftfCelular.getText();
        tel = tel.replace("(","");
        tel = tel.replace(")","");
        tel = tel.replace("-","");
        tel = tel.replace(" ","");
 
        activeUser = dao.getUserByTel(tel);
        jlUsuarioNome.setText(activeUser.getNome());
        jlPontuacaoUsuario.setText(Integer.toString(activeUser.getPontuacao())); 
    }//GEN-LAST:event_jButtonCarregarUsuarioActionPerformed

    private void btCadastrarLixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarLixoActionPerformed
        UsuarioDAO dao = new UsuarioDAO();
        LixeiraDAO lixeiraDao = new LixeiraDAO();
        dao.updateScore(activeUser.getId(),activeUser.getPontuacao());
        System.out.println("CAPACIDADE DA LIXEIRA: "+ Integer.toString(this.lixeira.getCapacidadeUtilizada()));
        lixeiraDao.updateCapacityUsed(this.lixeira.getId(),this.lixeira.getCapacidadeUtilizada());
        jButtonCarregaLixeira.doClick();
        jButtonCarregarUsuario.doClick();
    }//GEN-LAST:event_btCadastrarLixoActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        PrincipalScreen viewPrincipalScreen = new PrincipalScreen(activeUser);
        viewPrincipalScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LixeiraScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LixeiraScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LixeiraScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LixeiraScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LixeiraScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarLixo;
    private javax.swing.JButton jButtonCarregaLixeira;
    private javax.swing.JButton jButtonCarregarUsuario;
    private javax.swing.JComboBox<Object> jComboBoxLixeiras;
    private javax.swing.JComboBox<String> jComboBoxTipoDeLixo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCapUtil;
    private javax.swing.JLabel jLabelCapUtilizada;
    private javax.swing.JLabel jLabelDigiteCelular;
    private javax.swing.JLabel jLabelSelecionarLixeira;
    private javax.swing.JLabel jLabelTipoDoLixo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDadosLixeira;
    private javax.swing.JPanel jPanelDadosUsuario;
    private javax.swing.JPanel jPanelDadosdoLixo;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JFormattedTextField jftfCelular;
    private javax.swing.JLabel jlPontuacao;
    private javax.swing.JLabel jlPontuacaoUsuario;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JLabel jlUsuarioNome;
    private javax.swing.JLabel lbCapacidadeTotal;
    private javax.swing.JLabel lbCapacidadeTotalResult;
    // End of variables declaration//GEN-END:variables
}
