/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import model.bean.Usuario;

/**
 *
 * @author Leandro Max
 */
public class PrincipalScreen extends javax.swing.JFrame {

    private Usuario activeUser;
    /**
     * Creates new form Princ
     * ipalScreen
     * @param activeUser
     */
    public PrincipalScreen(Usuario activeUser) {
        initComponents();
        this.activeUser = new Usuario();
        this.activeUser = activeUser;
        jlNomeUsuario.setText(this.activeUser.getNome());
        jlPontuacaoUsuario.setText(Integer.toString(this.activeUser.getPontuacao()));
    }
    
    public PrincipalScreen() {
        initComponents();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jlNomeUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlPontuacaoUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiCadastrarLixeira = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNome.setText("Nome:");
        jPanel2.add(jlNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jlNomeUsuario.setText("jLabel2");
        jPanel2.add(jlNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel3.setText("Pontuação:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jlPontuacaoUsuario.setText("jLabel4");
        jPanel2.add(jlPontuacaoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 230, 100);

        jMenuFile.setText("File");

        jMenuItem1.setText("Cadastrar Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItem1);

        jmiCadastrarLixeira.setText("Cadastrar Lixeira");
        jmiCadastrarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarLixeiraActionPerformed(evt);
            }
        });
        jMenuFile.add(jmiCadastrarLixeira);

        jMenuBar1.add(jMenuFile);

        jMenuExit.setText("Exit");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemExit);

        jMenuBar1.add(jMenuExit);

        jMenu2.setText("Navegação");

        jMenuItem2.setText("Interface da Lixeira");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(250, 160));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastroUsuarioScreen cadastroUsuarioScreen = new CadastroUsuarioScreen(activeUser);
        cadastroUsuarioScreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        //LixeiraScreen telaLixeira = new LixeiraScreen();
        LixeiraScreen viewInterfaceLixeira = new LixeiraScreen(activeUser);
        viewInterfaceLixeira.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiCadastrarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarLixeiraActionPerformed
        CriaLixeiraScreen viewCadastroLixeira = new CriaLixeiraScreen(activeUser);
        viewCadastroLixeira.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiCadastrarLixeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeUsuario;
    private javax.swing.JLabel jlPontuacaoUsuario;
    private javax.swing.JMenuItem jmiCadastrarLixeira;
    // End of variables declaration//GEN-END:variables
}
